pipelines:
  - name: big_book
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
            - echo $step_name $step_node_id
            - wget https://norvig.com/big.txt
            - cat big.txt
