pipelines:
  - name: Conditional_Workflow_Example
    steps:
      - name: step1
        type: Bash
        execution: 
          onExecute:
            - echo 'step1'
            - add_run_variables 'var1=1'
      - name: step2
        type: Bash
        configuration: 
          condition: 'var1==1'
          inputSteps: 
            - name: step1
        execution:
          onExecute:
            - echo "Success"
      - name: step3
        type: Bash
        configuration: 
          condition: 'var1==2'
          inputSteps: 
            - name: step1
        execution:
          onExecute:
            - echo "Success"
  - name: PIPE_9455_Workflow_03
    steps:
      - name: step1
        type: Bash
        configuration:
          allowFailure: true
        execution:
          onExecute:
            - echo 'step1'
      - name: step2
        type: Bash
        configuration:
          allowFailure: true
          inputSteps:
          - name: step1
            status:
              - success
              - error
              - failure
              - timeout
        execution:
          onExecute:
            - echo 'failure'
            - exit 1  

