pipelines:
  - name: condition1
    steps: 
     - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
            - add_run_variables 'var1=1'
      - name: step2
        type: Bash
        configuration:
          condition: 'var1 == 1' // Any logical boolean expression that results to a boolean
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo 'success'