pipelines:
  - name: condition3
    configuration:
      environmentVariables:
        readOnly:
          shashank_env_1:
            default: 2
            allowCustom: true
    steps:
      - name: step1
        type: Bash
        configuration:
          environmentVariables:
              shashank_env_2: 
                default: 3
                allowCustom: true
        execution:
            onExecute:
              - echo 'step1'
              - echo $shashank_env_1
              - echo $shashank_env_2
      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
          conditon: 'shashank_env_1==2'
        execution:
          onExecute:
            - echo 'step2'
            - echo $shashank_env_1
            - echo $shashank_env_2
        