pipelines:
  - name: testing_conditional_variables
    steps:
      - name: step1
        type: Bash
        configuration:
          environmentVariables:
            shashank_env:
              allowCustom: true
        execution:
          onExecute:
            - echo $shashank_env
      - name: step2
        type: Bash
        configuration:
          condition: '$shashank_env==2'
          inputSteps: 
            - name: step1
        execution:
          onExecute:
            - echo "Success"

