pipelines:
  - name: testing_conditional_variables
    steps:
      - name: step1
        type: Bash
        configuration:
          environmentVariables:
            shashank_env:
              allowCustom: true
              default: 2
        execution:
          onExecute:
            - echo $shashank_env
            - add_run_variables "key_a=1"

