pipelines:
  - name: testing_conditional_variables
    steps:
      - name: step1
        type: Bash
        configuration:
          environmentVariables:
            shashank_env:
              allowCustom: true
              default: 2
        execution:
          onExecute:
            - echo $shashank_env
            - add_run_variables "key_a=1"
      - name: step2
        type: Bash
        configuration:
          condition: 'key_a==1'
          inputSteps: 
            - name: step1
        execution:
          onExecute:
            - echo "Success"
      - name: step3
        type: Bash
        configuration: 
          condition: 'shashank_env==3'
        execution:
          onExecute:
            - echo "step3 done"
            - echo $shashank_env

