pipelines:
  - name: testing_conditional_variables
    steps:
      - name: step1
        type: Bash
        configuration:
          environmentVariables:
            shashank_env:
              default: 2
              allowCustom: true
        execution:
          onExecute:
            - echo $shashank_env
            - add_run_variables key=1
      - name: step2
        type: Bash
        configuration:
          condition: 'key==1'
          inputSteps: 
            - name: step1
        execution:
          onExecute:
            - echo "Success"
      - name: step3
        type: Bash
        configuration:
          inputSteps: 
            - name: step1
        execution:
          onExecute:
            - echo '$key'

