pipelines:
  - name: testing_conditional_variables
    steps:
      - name: step1
        type: Bash
        configuration:
          environmentVariables:
            shashank_env:
              default: 1
              allowCustom: true
        execution:
          onExecute:
            - echo $shashank_env
            - add_run_variables 'shashank_env=$shashank_env'
      - name: step2
        type: Bash
        configuration:
          condition: '$shashank_env==2'
          inputSteps: 
            - name: step1
        execution:
          onExecute:
            - echo "Success"

