pipelines:
  - name: simple_pipeline_with_3_Steps
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
            - echo $step_name $step_node_id
      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution:
          onExecute:
            - echo 'step2'
            - echo $step_name $step_node_id
      - name: step3
        type: Bash
        configuration: 
          inputSteps:
            - name: step2
        execution:
          onExecute:
            - echo 'step3'
            - echo $step_name $step_node_id
      - name: step4
        type: Bash
        configuration: 
          inputSteps:
            - name: step3
        execution:
          onExecute:
            - echo 'step3'
            - echo $step_name $step_node_id
