pipelines:
 - name: pipeline_slack_test_2
 - steps:
    - name: trigger_all
      configuration:
        timeoutSeconds: 1800
      type: Bash
      execution:
        onExecute:
          - echo "Used solely to connect create and delete steps"
    - name: repositories_actions_create
      configuration:
        priority: 1
        timeoutSeconds: 1800
        inputSteps:
          - name: trigger_all
      type: Bash
      execution:
        onStart:
          - echo "started"
        onExecute:
          - echo "executing"
        onFailure:
          - echo "failed"
        onSuccess:
          - echo "succeeded"
        onComplete:
          - echo "completed"
    - name: jfdev_ci_commons_bogus_build
      type: Bash
      configuration:
        timeoutSeconds: 1800
        inputSteps:
          - name: trigger_all
      execution:
        onExecute:
          - echo "executing"
    - name: jfdev_ci_commons_recover_release
      type: Bash
      configuration:
        requiresApproval:
          approvers:
            - admin
          notifications:
            - integrationName: shashank_int
        timeoutSeconds: 1800
        nodePool: ci_release
        inputSteps:
          - name: trigger_all
      execution:
        onExecute:
          - echo "123"
