pipelines:
  - name: two_step_pipeline
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo 'step1'
            - echo $step_name $step_node_id
      - name: step2
        type: Bash
        configuration:
            inputSteps: 
              - name: step1
        execution:
          onExecute:
            - echo 'step2'
            - echo 'success'
